# Generated by Django 4.2.26 on 2025-11-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gamerecord',
            new_name='game_record_user_id_92bc95_idx',
            old_name='game_records_user_id_e3b9ad_idx',
        ),
        migrations.RenameIndex(
            model_name='gamerecord',
            new_name='game_record_game_ty_91f3f7_idx',
            old_name='game_records_game_ty_2bd4fc_idx',
        ),
        migrations.RenameIndex(
            model_name='gamerecord',
            new_name='game_record_played__fd4eab_idx',
            old_name='game_records_played__dd0d70_idx',
        ),
    ]
