# Generated by Django 4.2.26 on 2025-11-12 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='饮水量(ml)')),
                ('type', models.CharField(default='custom', max_length=20, verbose_name='杯子类型')),
                ('drink_name', models.CharField(default='饮水', max_length=50, verbose_name='饮品名称')),
                ('drink_icon', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标')),
                ('caffeine_mg', models.IntegerField(blank=True, null=True, verbose_name='咖啡因含量(mg)')),
                ('recorded_at', models.DateTimeField(verbose_name='记录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '饮水记录',
                'verbose_name_plural': '饮水记录',
                'db_table': 'water_intakes',
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='water_intak_user_id_dd4971_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmokingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('mood', models.CharField(blank=True, choices=[('relaxed', '放松'), ('stressed', '压力大'), ('social', '社交'), ('habit', '习惯'), ('other', '其他')], max_length=20, null=True, verbose_name='心情')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='地点')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('recorded_at', models.DateTimeField(verbose_name='记录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoking_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '抽烟记录',
                'verbose_name_plural': '抽烟记录',
                'db_table': 'smoking_records',
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='smoking_rec_user_id_435bb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DrinkOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='饮品名称')),
                ('amount', models.IntegerField(default=300, verbose_name='容量(ml)')),
                ('icon', models.CharField(blank=True, max_length=20, null=True, verbose_name='图标')),
                ('caffeine_mg', models.IntegerField(blank=True, null=True, verbose_name='咖啡因(mg)')),
                ('is_default', models.BooleanField(default=False, verbose_name='系统预设')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drink_options', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '饮品选项',
                'verbose_name_plural': '饮品选项',
                'db_table': 'drink_options',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BowelMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('normal', '正常'), ('hard', '偏硬'), ('soft', '偏软'), ('watery', '水样'), ('dry', '干燥')], default='normal', max_length=20, verbose_name='类型')),
                ('color', models.CharField(choices=[('brown', '棕色'), ('yellow', '黄色'), ('green', '绿色'), ('black', '黑色'), ('red', '红色'), ('other', '其他')], default='brown', max_length=20, verbose_name='颜色')),
                ('difficulty', models.IntegerField(choices=[(1, '等级1'), (2, '等级2'), (3, '等级3'), (4, '等级4'), (5, '等级5')], verbose_name='困难程度')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('recorded_at', models.DateTimeField(verbose_name='记录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowel_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '排便记录',
                'verbose_name_plural': '排便记录',
                'db_table': 'bowel_movements',
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='bowel_movem_user_id_f3a98d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('water', '饮水记录'), ('bowel', '排便记录'), ('smoking', '抽烟记录'), ('slack', '摸鱼记录'), ('game', '游戏记录'), ('custom', '自定义')], max_length=20, verbose_name='类别')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('complete', '完成'), ('start', '开始'), ('stop', '停止')], max_length=20, verbose_name='动作')),
                ('details', models.JSONField(default=dict, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '活动记录',
                'verbose_name_plural': '活动记录',
                'db_table': 'activities',
                'indexes': [models.Index(fields=['user', 'category'], name='activities_user_id_935e47_idx'), models.Index(fields=['created_at'], name='activities_created_78a0e3_idx')],
            },
        ),
    ]
