# Generated by Django 4.2.26 on 2025-11-12 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='摸鱼时长(分钟)')),
                ('mood', models.CharField(blank=True, choices=[('relaxed', '放松'), ('bored', '无聊'), ('stress', '缓解压力'), ('social', '社交'), ('other', '其他')], max_length=20, null=True, verbose_name='心情')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='简短描述')),
                ('recorded_at', models.DateTimeField(verbose_name='记录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '摸鱼记录',
                'verbose_name_plural': '摸鱼记录',
                'db_table': 'slack_records',
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='slack_recor_user_id_1ff98d_idx')],
            },
        ),
    ]
