# Generated by Django 4.2.26 on 2025-11-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_room_id_584819_idx',
            old_name='chat_messa_room_id_df4f7e_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_user_id_790302_idx',
            old_name='chat_messa_user_id_5759ad_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroommember',
            new_name='chat_room_m_room_id_e52f32_idx',
            old_name='chat_room__room_id_680ed5_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroommember',
            new_name='chat_room_m_user_id_00a852_idx',
            old_name='chat_room__user_id_b6c852_idx',
        ),
        migrations.RenameIndex(
            model_name='onlineuser',
            new_name='online_user_last_se_33ba87_idx',
            old_name='online_use_last_se_99f8ad_idx',
        ),
        migrations.RenameIndex(
            model_name='onlineuser',
            new_name='online_user_current_4a7732_idx',
            old_name='online_use_current_f9c09d_idx',
        ),
    ]
